import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {FaSearch} from 'react-icons/fa'

export async function getStaticProps() {
  var res = await import("../public/database.json")
  var data = res.default
  var crypto = require('crypto')

  data.map((book, i) => {
    if (book.Id == "") {
      book.Id = crypto.randomUUID()
      const fs = require('fs')
      fs.writeFileSync("public/database.json", JSON.stringify(data, null, 4))
    }
  })

  return {
    props: {books: data}
  }
}

export function Book({id, title, author, img}) {
  return (
    <div>
        <a className={styles.book_link} href={"books/" + id}>
          <img src={img}></img>
        </a>
    </div>
  )
}

export default function Home({books}) {
  return (
    <div>
      <Head>
        <title>ScrollHub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <div className={styles.container}>
        <input className={styles.search_bar} placeholder='Search for books'></input>
        <button className={styles.search_button}><FaSearch /></button>
      </div>

      <div className={styles.container_two}>
        <ul className={styles.book_list}>
          {books.map((book, i) => {
            return <li><Book id={book.Id} title={book.Title} author={book.Author} img={book.Image}/></li>
          })}
        </ul>
      </div>
    </div>
  )
}
